name: Fetch News Content

on:
  schedule:
    - cron: '0 * * * *'  # 每小时触发

jobs:
  fetch_news_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Python Dependencies
        run: |
          pip install requests feedparser beautifulsoup4
      
      - name: Fetch and Save Article Content
        run: python fetch_news_content.py
      
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add articles_content.txt
          git commit -m "Update news content" -a || echo "No changes to commit"
          git push
