name: Run Multiple Scripts with Different Schedules

on:
  schedule:
    - cron: '0 * * * *'   # 每小时执行一次
    - cron: '0 */4 * * *' # 每4小时执行一次

jobs:
  fetch_news_links_hourly:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 * * * *'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install requests feedparser
      - name: Fetch and process news links
        run: python fetch_news.py
      - name: Commit and push changes
        run: |
          git config --local user.email 'actions@github.com'
          git config --local user.name 'GitHub Actions'
          git add accumulated_links.txt
          git diff-index --quiet HEAD || git commit -m "Update list of processed news links"
          git push

  process_and_fetch_articles_every_four_hours:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 */4 * * *'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Process new links and fetch articles
        run: python process_new_articles.py
      - name: Commit and push new articles if changes
        run: |
          git config --local user.email 'actions@github.com'
          git config --local user.name 'GitHub Action'
          git add articles.md processed_links.txt
          git diff-index --quiet HEAD || git commit -m "Update new articles and processed links"
          git push
