name: Run Python Script

on:
  schedule:
    - cron: '0 * * * *'  # 这将会在每小时的第0分钟触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install feedparser requests readability-lxml

    - name: Execute Python script
      run: python your_python_script.py  # 把 your_python_script.py 替换为你的 Python 脚本的文件名
