name: Fetch News Content

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  fetch_news_content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4
      
      - name: Fetch article contents and accumulate
        run: python fetch_content.py

      - name: Commit and push changes if there are new contents
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'
          git add accumulated_content.txt
          git diff --staged --quiet || git commit -m "Update accumulated article contents"
          git push

      - name: Clear accumulated contents file daily
        if: github.event.schedule == '0 0 * * *'
        run: |
          truncate -s 0 accumulated_content.txt
          git commit -m "Clear accumulated contents" accumulated_content.txt || echo "No changes to commit"
          git push || echo "No changes to push"
