name: Run Scripts with Different Schedules

on:
  schedule:
    - cron: '0 * * * *'  # Execute fetch_news_links_hourly at the 0th minute of every hour
    - cron: '5 * * * *'  # Execute run_other_script_every_hour at the 5th minute of every hour

jobs:
  fetch_news_links_hourly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          pip install requests feedparser selenium webdriver_manager

      - name: Fetch and process news links
        run: |
          python fetch_news.py

      - name: Configure Git
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'

      - name: Fetch and merge remote changes
        run: |
          git fetch origin
          git merge origin/main --no-edit || echo "No changes to merge"

      - name: Commit and push changes
        run: |
          git add accumulated_links.txt
          git commit -m "Update list of processed news links" || echo "No changes to commit"
          git push

  run_other_script_every_hour:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget gnupg
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          pip install requests selenium webdriver_manager lxml readability-lxml beautifulsoup4

      - name: Run other script
        run: |
          python other_script_every_hour.py

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

      - name: Fetch and merge remote changes
        run: |
          git fetch origin
          git merge origin/main --no-edit || echo "No changes to merge"

      - name: Commit and push if changes
        run: |
          git add .
          git commit -m "Update other script changes" || echo "No changes to commit"
          git push
